spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/user
    username: fayupable
    password: fayupable
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

server:
  port: 8100

auth:
  token:
    expirationInMils: ${JWT_EXPIRATION}
    jwtSecret: ${JWT_SECRET}


